server:
  address: localhost
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  devtools:
    livereload:
      enabled: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # SessionFactory가 시작될 때, Drip, Create, Alter 종료될 때 Drop
                            # SpringBoot 서버과 시작될 때마다 테이블들을 새로 만들기 때문에
                            # 편의를 위해서 서버가 시작될 때마다 Data를 자동으로 DB에 넣어주는 기능 활용하면 좋음!
                            
    defer-datasource-initialization: true # boot 버전이 2.5.0 이상이면 하이버네이트 초기화 과정보다 data.sql이 먼저 실행되어
                                          # 오류 발생 가능 -> 이 설정 넣어서 해결!         
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#jwt:
#  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400

springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false

logging:
  level:
    me.silvernine: DEBUG